-- Generated by _tools/gen_cc_spells.py from the Forever game tables, build 1.60.1.70235.
-- Crowd control: spell id -> true, every rank. The big icon on a plate shows these when
-- they are yours; the small debuff row leaves them out.
local ADDON, ns = ...
ns.ccSpells = {
	[710] = true, [18647] = true,   -- banish
	[5211] = true, [6798] = true, [8983] = true,   -- bash
	[2094] = true,   -- blind
	[1277331] = true, [1277332] = true, [1277333] = true, [1277334] = true, [1277335] = true,   -- chastise
	[1833] = true,   -- cheap shot
	[12809] = true,   -- concussion blow
	[6789] = true, [17925] = true, [17926] = true,   -- death coil
	[339] = true, [1062] = true, [5195] = true, [5196] = true, [9852] = true, [9853] = true,   -- entangling roots
	[5782] = true, [6213] = true, [6215] = true,   -- fear
	[1499] = true, [14310] = true, [14311] = true,   -- freezing trap
	[122] = true, [865] = true, [6131] = true, [10230] = true,   -- frost nova
	[11071] = true, [12494] = true,   -- frostbite
	[1776] = true, [1777] = true, [8629] = true, [11285] = true, [11286] = true,   -- gouge
	[853] = true, [5588] = true, [5589] = true, [10308] = true,   -- hammer of justice
	[2637] = true, [18657] = true, [18658] = true,   -- hibernate
	[2812] = true, [10318] = true,   -- holy wrath
	[5484] = true, [17928] = true,   -- howl of terror
	[1122] = true,   -- inferno
	[20252] = true, [20616] = true, [20617] = true, [427745] = true,   -- intercept
	[427746] = true,   -- intercept stun
	[5246] = true,   -- intimidating shout
	[19577] = true, [24394] = true,   -- intimidation
	[408] = true, [8643] = true,   -- kidney shot
	[605] = true, [10911] = true, [10912] = true,   -- mind control
	[16689] = true, [16810] = true, [16811] = true, [16812] = true, [16813] = true, [17329] = true,   -- nature's grasp
	[118] = true, [12824] = true, [12825] = true, [12826] = true, [28271] = true, [28272] = true,   -- polymorph
	[28270] = true,   -- polymorph: cow
	[9005] = true, [9823] = true, [9827] = true,   -- pounce
	[8122] = true, [8124] = true, [10888] = true, [10890] = true,   -- psychic scream
	[20066] = true,   -- repentance
	[2070] = true, [6770] = true, [11297] = true,   -- sap
	[1513] = true, [14326] = true, [14327] = true,   -- scare beast
	[19503] = true,   -- scatter shot
	[6358] = true,   -- seduction
	[9484] = true, [9485] = true, [10955] = true,   -- shackle undead
	[440488] = true,   -- shockwave
	[19244] = true, [19647] = true,   -- spell lock
	[1098] = true, [11725] = true, [11726] = true,   -- subjugate demon
	[2878] = true, [5627] = true, [10326] = true,   -- turn undead
}
